name: Maven Hello World CI/CD

# Define triggers for code changes
on:
  push:
    branches: [ master, test2 ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# Grant permissions to allow pushing images to GitHub Container Registry (GHCR)
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  # Converts the repository name to lowercase to prevent Docker naming errors
  IMAGE_NAME: ${{ github.repository }}
  Sample11: ${{ vars.SAMPLE }}
  
jobs:
  # CONTINUOUS INTEGRATION (CI)
  #Approval:
  #  runs-on: self-hosted
  #  # CRITICAL: This links the job to your protected environment rules
  #  environment: production
  #  steps:
  #  - run: echo "Deploying to production server now that it is approved!"
  build-and-test:
    runs-on: ${{ matrix.os }}
    #needs: Approval

    strategy:
      # If one combination fails, don't cancel the others automatically
      fail-fast: false  
      matrix:
        # Define the variables to combine
        os: [ubuntu-latest]
        java-version: ['21']
        
        # Optional: Include a specific extra combination
        exclude:
          - os: ubuntu-latest
            java-version: '11'
            #experimental: true
    continue-on-error: true
    
    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven' # Automatically caches .m2 dependencies to save time

      - name: Compile and Run Tests
        run: mvn clean test

      - name: Package Application
        run: mvn package -DskipTests # Packages code into a target/ target JAR

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-jar
          path: target/*.jar
      # --- NEW DOCKER STEPS START HERE ---
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata (Tags & Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  Priniting-context:
    runs-on: self-hosted
    needs: [build-and-test]
    steps:
      - name: printing context
        run: |
              echo "${{ vars.Sample11 }}"
              echo "${{ toJSON(github) }}"



 
